---
- hosts: backend
  become: true
  tasks:
  - name: install JDK1.8 and git
    apt:
      name: "{{ item }}"
      update_cache: yes
      state: latest
    with_items:
      - openjdk-8-jre
      - git
  - name: remove old code
    shell: rm -r B-basic-quiz
  - name: clone code from github
    shell: git clone https://github.com/ghjhhyuyuy/B-basic-quiz.git
  - name: build project
    shell: ./gradlew build
    args:
      chdir: ~/B-basic-quiz
  - name: start jar
    shell: nohup java -jar basic-quiz-0.0.1-SNAPSHOT.jar>meg.txt &
    args:
      chdir: ~/B-basic-quiz/build/libs
- hosts: frontend
  become: true
  tasks:
  - name: install nodejs && git   
    apt:
      name: "{{ item }}"
      update_cache: yes
      state: latest
    with_items:
      - nodejs
      - git
  - name: remove old code
    shell: rm -r F-basic-quiz
  - name: clone code from github
    shell: git clone https://github.com/ghjhhyuyuy/F-basic-quiz.git
  - name: change branch to deploy
    shell: git checkout deploy
    args:
      chdir: ~/F-basic-quiz
  - name: install
    shell: npm install
    args:
      chdir: ~/F-basic-quiz
  - name: start project
    shell: npm start
    args:
      chdir: ~/F-basic-quiz
